<?php

namespace Tests\Feature\Templates;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Sendportal\Base\Facades\Sendportal;
use Sendportal\Base\Models\Campaign;
use Sendportal\Base\Models\Template;
use Tests\TestCase;

class TemplatesControllerTest extends TestCase
{
    use RefreshDatabase,
        WithFaker;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /** @test */
    public function a_logged_in_user_can_see_template_index()
    {
        $response = $this->get(route('sendportal.templates.index'));

        $response->assertOk();
    }

    /** @test */
    public function the_index_lists_existing_templates()
    {
        $template = factory(Template::class)->create([
            'workspace_id' => Sendportal::currentWorkspaceId()
        ]);

        $response = $this->get(route('sendportal.templates.index'));

        $response->assertOk();
        $response->assertSee($template->name);
    }

    /** @test */
    public function a_logged_in_user_can_see_the_create_form()
    {
        $response = $this->get(route('sendportal.templates.create'));

        $response->assertOk();
        $response->assertSee('New Template');
        $response->assertSee('Template Name');
        $response->assertSee('Content');
    }

    /** @test */
    public function a_logged_in_user_can_store_a_new_template()
    {
        $data = [
            'name' => $this->faker->name,
            'content' => $this->faker->sentence
        ];

        $response = $this->post(route('sendportal.templates.store'), $data);

        $response->assertRedirect(route('sendportal.templates.index'));

        $this->assertDatabaseHas('sendportal_templates', [
            'name' => $data['name'],
            'content' => $data['content'],
            'workspace_id' => Sendportal::currentWorkspaceId()
        ]);
    }

    /** @test */
    public function storing_is_validated()
    {
        $data = [
            'name' => $this->faker->name,
        ];

        $response = $this->post(route('sendportal.templates.store'), $data);

        $response->assertSessionHasErrors('content');

        $data = [
            'content' => $this->faker->sentence
        ];

        $response = $this->post(route('sendportal.templates.store'), $data);

        $response->assertSessionHasErrors('name');
    }

    /** @test */
    public function a_logged_in_user_can_see_the_edit_form()
    {
        $template = factory(Template::class)->create([
            'workspace_id' => Sendportal::currentWorkspaceId()
        ]);

        $response = $this->get(route('sendportal.templates.edit', $template->id));

        $response->assertOk();

        $response->assertSee($template->name);
        $response->assertSee($template->content);
    }

    /** @test */
    public function a_logged_in_user_can_update_a_template()
    {
        $template = factory(Template::class)->create([
            'workspace_id' => Sendportal::currentWorkspaceId()
        ]);

        $data = [
            'name' => $this->faker->name,
            'content' => $this->faker->sentence
        ];

        $response = $this->put(route('sendportal.templates.update', $template->id), $data);

        $response->assertRedirect(route('sendportal.templates.index'));

        $this->assertDatabaseMissing('sendportal_templates', [
            'id' => $template->id,
            'name' => $template->name,
            'content' => $template->content
        ]);
        $this->assertDatabaseHas('sendportal_templates', $data + ['id' => $template->id, 'workspace_id' => Sendportal::currentWorkspaceId()]);
    }

    /** @test */
    public function updates_are_validated()
    {
        $template = factory(Template::class)->create([
            'workspace_id' => Sendportal::currentWorkspaceId()
        ]);

        $data = [
            'name' => $this->faker->name,
        ];

        $response = $this->put(route('sendportal.templates.update', $template->id), $data);

        $response->assertSessionHasErrors('content');

        $data = [
            'content' => $this->faker->sentence
        ];

        $response = $this->put(route('sendportal.templates.update', $template->id), $data);

        $response->assertSessionHasErrors('name');
    }

    // Destroy.

    /** @test */
    public function a_logged_in_user_can_delete_a_template()
    {
        $template = factory(Template::class)->create([
            'workspace_id' => Sendportal::currentWorkspaceId()
        ]);

        $response = $this->delete(route('sendportal.templates.destroy', $template->id));

        $response->assertRedirect(route('sendportal.templates.index'));

        $this->assertDatabaseMissing('sendportal_templates', [
            'id' => $template->id,
            'name' => $template->name
        ]);
    }

    /** @test */
    public function a_logged_in_user_cannot_delete_a_template_if_it_is_used()
    {
        $template = factory(Template::class)->create([
            'workspace_id' => Sendportal::currentWorkspaceId()
        ]);

        $campaign = factory(Campaign::class)->create([
            'template_id' => $template->id
        ]);

        $response = $this->from(route('sendportal.templates.index'))
            ->delete(route('sendportal.templates.destroy', $template->id));

        $response->assertRedirect(route('sendportal.templates.index'))
            ->assertSessionHasErrors(['template']);

        $this->assertDatabaseHas('sendportal_templates', [
            'id' => $template->id,
            'name' => $template->name
        ]);
    }

    /** @test */
    public function a_template_name_must_be_unique_for_a_workspace()
    {
        $template = factory(Template::class)->create(['workspace_id' => Sendportal::currentWorkspaceId()]);

        $request = [
            'name' => $template->name,
        ];

        $response = $this->post(route('sendportal.templates.store'), $request);

        $response->assertRedirect()
            ->assertSessionHasErrors('name');
        $this->assertEquals(1, Template::where('name', $template->name)->count());
    }
}
